### ISSUE TITLE
Homepage Image

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/janis#103]
_Continuation of #37..._

homepage – image: [Ladybird Lake trail](https://www.flickr.com/photos/austintexasgov/13248971115/in/album-72157642552791885/)

- Use flicker to download the appropriate size

- [x] mobile height: 260

- [x] tablet height: 400

- [x] desktop height: 444

- [x] image overlay is hex #240B33 at 30% opacity

![homepage hero mockup](https://user-images.githubusercontent.com/20911665/35680392-d6180b64-071f-11e8-9643-c978b5236632.png)

**Comment by mateoclarke** [comment]
@cthibaultatx, there was discussion in Slack around a few options for this image. Will you post here when a selection is made?

**Comment by succarwagner** [comment]
@cthibaultatx could you please catch me up on homepage concept and any briefs on image selection? Thanks.
