### ISSUE TITLE
Host app at alpha.austin.gov

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/janis#112]
- [x] `CNAME` alpha.austin.gov to alpha.austin.gov.herokudns.com
- [x] Ensure https works (this might require more fixes)

**Comment by benweatherman** [comment]
I contacted @escribbles to get access to the DNS for alpha.austin.gov. We're working on getting that fixed up.

There's a memo going out Feb 5 and it'd be sweet to get something live before that.

**Comment by divyarathanlal** [comment]
Ticket #1808333 to get the DNS working has been submitted to the linux team.

**Comment by mateoclarke** [comment]
@divyarathanlal Is there anyone we can reach out to in order to make sure they understand the ask and to help expedite the process? Feb 5 is less than 3 business days.

**Comment by benweatherman** [comment]
Jason Glass from Linux CTM is working on it right meow

**Comment by benweatherman** [comment]
<img width="544" alt="secure-alpha" src="https://user-images.githubusercontent.com/272675/35751529-8cebb238-081e-11e8-9ad2-7eb2bf2dff3c.png">
