### ISSUE TITLE
Revisiting Static builds vs Server Side Rendering with React

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/janis#132]
@benweatherman and I had a good discussion today about architecture decisions that effect how we deploy. 

Here is a rough diagram of how our two systems looks now using React Static: 

![img_9622](https://user-images.githubusercontent.com/5697474/35834730-a42248e2-0a9c-11e8-841d-d81fada49d8f.JPG)

Joplin provides data to Janis via GraphQL. Janis has a static.config.js file that maps data to page routes for React Static's build step. In "developer mode," Janis behaves like a (mostly) normal React app. In "production mode," Janis builds all the files required for any page on the website. 

This presents two issues that aren't ideal:
1. In **developer mode**, we don't experience the site as our end users do. If someone files a bug and we fix it locally, we should also run a built version to make sure the bug is fixed for the prod environment. The fact that there are two differing strategies for how the app works in local dev vs production is contrary to the type of dev feedback loop we are trying to create with tools like Docker.
2. In **production mode**, we haven't figured out a strategy to target select pages to be rebuilt. If, for example, content is updated in Spanish, we should only have to rebuild the spanish version of the site. Or even better, just the pages effected by the data change. After doing some research about how the  React Static project might try to solve this issue, I'm worried that there might not be a good, out-of-the-box solution. 
    - [Issue: Delta builds for very large sites](https://github.com/nozzle/react-static/issues/53)
    - (TL;DR is that because they have such an agnostic view about where data comes from, they are going to focus on faster builds instead of deltas. Any delta stuff sounds like it would have to happen in a separate build script.)

The hypothesis for trying out the static build strategy was that we could rebuild the site fast enough so that the time required to publish for an editor to the time an edit is live was a reasonable wait.  This feels more uncertain, at least without a good strategy for "delta builds." Knowing what I do now, I should've researched this more before implementing React Static.

The alternative pattern would be what a more standard CMS uses with caching using Varnish, illustrated here by Ben...

![img_4286](https://user-images.githubusercontent.com/5697474/35834925-782e216a-0a9d-11e8-98a2-50377c98afa8.JPG)

In this last whiteboard photo, we started listing out the features that are important for our front end system. If we were only concerned about SEO and Server Loads (ie traffic) than React Static would be the winner. With other considerations, perhaps we should reevaluate SSR frameworks like Next.js.

![img_0386](https://user-images.githubusercontent.com/5697474/35835005-e3e1d7d0-0a9d-11e8-8a98-adc0d9253eb8.JPG)

_Thanks for reading my essay_ 🍏

**Comment by mateoclarke** [comment]
Gatsby has similar issues to React Static in this regard:
- [Issue: gatsby build very slow](https://github.com/gatsbyjs/gatsby/issues/179)
- [Issue: Support incremental production builds](https://github.com/gatsbyjs/gatsby/issues/179)

**Comment by ifsimicoded** [comment]
This might be moot if we don't go with react static -- but should our primary nav also be statically built? It looks like the current app fetches the data for the menu after the [component mounts](https://github.com/cityofaustin/janis/blob/fdf902873c3190bed3fca388b2e417f61fb9e84e/src/js/page_sections/Navmenu.js#L29).

**Comment by mateoclarke** [comment]
Yeah, I think that was the last thing I needed to work on before I started doubting whether React Static was the best long term solution. Brian had also talked about implementing Apollo, which would change how state gets passes as props into components.

I'd say the next time we update the Navigation (which there are designs for), we implement it the navigation as a nested object that gets passed to each page in the `static.config.js` even if it means changing how that works in the future.

**Comment by luqmaan** [comment]
Some questions from our discussion today:

- How does next.js generates etags? https://github.com/zeit/next.js/pull/1693

- Where do wagtail pages go in next.js?

  - Probably using custom routing on the server

- How does adding a new page in wagtail affect rendering time and the cache?

- How can we invalidate the entire cache? For example, if there is a typo in the global navigation? How will this affect next.js? Will this lead to huge CPU spikes?

- How much work will it take to get the existing react router 4 code to work with next.js?

- Is SSR impacted by the number of routes?

- How does static page building work? Is that impacted by the number of routes?

- What does interaction with 3rd party widgets look like?

- How does caching work?

- Can we make next consider targeting?

- How does SEO work with next.js?

- How does live preview work with next.js?

- How similar are dev and production in next.js?

- How does next.js work with non-JavaScript clients?

- What's the oldest browser that next.js supports?

  - IE 9 https://github.com/zeit/next.js/issues/436#issuecomment-269888128

**Comment by briaguya** [comment]
After some research into react-static builds I found a few things:
https://github.com/nozzle/react-static/pull/96 - apparently the basic template with 10,000 posts was building in 40s.
Also: https://github.com/nozzle/react-static/issues/53#issuecomment-339545967 - "99% of the time is actually spent in webpack and react SSR."

**Comment by easherma** [comment]
FWIW, in smaller projects I've gone back and forth on the merits of using React or similar frameworks if ultimately what is being generated is a static site. 

For instance, I'm a big fan of Hugo for a variety of reasons, not least of which is the extremely fast build time. Happy to talk about the pros and cons of either that I've noticed. 

Obviously trying a Hugo build of the frontend would be a pretty big departure, but I am curious if there was any thought/research into using such a purpose built tool. It seems to check all the boxes I see on the whiteboard. 

P.S. This may not be at all an appropriate place to leave this comment, so I'm happy to delete or direct this commentary elsewhere. ;-)

**Comment by mattclough1** [comment]
Just stumbled here apparently trying to achieve a similar thing and banging my head against the wall on the Wagtail preview issue. Did anyone ever figure out a good way to do previews, particularly with images?
