### ISSUE TITLE
User Story: As a resident, I want to understand the data collected by the City when I visit the website to make sure my privacy is maintained.

### ISSUE THREAD

**Issue by ashleecoa** [cityofaustin/janis#135]
We need to write and add a privacy policy to alpha. Here's the austintexas.gov one: http://austintexas.gov/page/privacy-policy

Should we consult with Law Department? 

See also https://github.com/cityofaustin/techstack/issues/173

**Comment by LCTrujillo** [comment]
Instead of re-writing this existing privacy policy, we just need to create a page for it on alpha.austin.gov

**Comment by mateoclarke** [comment]
Issue moved to [cityofaustin/techstack #252](https://github.com/cityofaustin/techstack/issues/252) via [**ZenHub**](https://www.zenhub.com/)
