### ISSUE TITLE
alpha.austin.gov homepage doesn't load until i click the link at the top

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/janis#156]
![homepage](https://user-images.githubusercontent.com/272675/36617767-60005b48-18ae-11e8-91ad-18103c5ae28e.gif)

**Comment by ifsimicoded** [comment]
not 100% sure what's going on here but it looks like it's not all pages. http://alpha.austin.gov/services/residential-curbside-collection-schedule
seems to do ok

**Comment by mateoclarke** [comment]
Sorry about this y'all. I should've checked the PR's Heroku deployment. There was an issue with the renderProps that I'm still kinda confused about. It had to do with the half done implementation of updating service tiles on the homepage. Fixed it by commented out code in the `static.config.js`:
https://github.com/cityofaustin/janis/commit/72a51aea54e04573aa3f11ac1fb876b8d977f382

One more strike against having different dev and prod build processes as discussed in #132
