### ISSUE TITLE
Feedback Form

### ISSUE THREAD

**Issue by benweatherman** [cityofaustin/janis#18]
- [x] UI Views for each state
- [x] Client form validation
- [x] Integration with Microservice Form Dispatcher
- [x] Workflow Analytics [[see below]](#issuecomment-350322802)
- [ ] figure out how we want to log email addresses -- currently shows in issue, which isn't very private.
- [ ] determine what we want to do in production vs development mode.

### Mockup
![screen shot 2018-01-11 at 9 20 31 am](https://user-images.githubusercontent.com/20911665/34996233-9c088bd4-fa9e-11e7-83c3-661ec9f78264.png)

**language translation only shows up as an option on a translated paged (re: see original mock options)**

### Step-by-step

1. User opts to submit feedback on page
2. Following options pop up:
  - Information on this page
  - Language translation (only shows up if page is translated from English to another language)
  - Technical issue
  - Something else
3. User chooses option which prompts a specific ask on the feedback form' (screen 4 above) =

- [ ] If selected "information on this page" = How can we improve this page?

- [ ] If selected "technical issue" = What technical issue are you having?

- [ ] If page is translated to a non-English language, and selected "language translation" = How can this page translation be improved?

- [ ] If selected "something else" = How can we help you?

  - Field appears with notification that feedback is public
  - Description field - rich text - required 
4. User sends feedback, form captures
  - Type of feedback
  - Feedback itself
  - URL, Device, Browser, OS

### More Info

Feedback form only shows up on Service Pages or other Page Templates–not topic or theme pages

Check out [further comments & context](https://docs.google.com/document/d/1t1FwkMRrGwRyh3NbJwqaSDHLTnLU2DkplPq_aRRcJj8/edit#)

**Comment by cthibaultatx** [comment]
![screen shot 2017-11-28 at 1 00 46 pm](https://user-images.githubusercontent.com/20911665/33338791-bc604030-d43c-11e7-8888-46ed7ce54daa.png)

**Comment by mattlangan** [comment]
I believe the plan is for this form to submit to the [Form Dispatcher](https://github.com/cityofaustin/forms-api-dispatch), which will then kick the submission off to the [GitHub API Issue Creator](https://github.com/cityofaustin/api-github-issue) service. Initial documentation is available in the repositories and includes required and optional params and server responses.

**Comment by amenity** [comment]
It looks like this issue misses another requested function; returning the issue URL to user. 
 
Returns link to issue in website submission confirmation modal: 
_“Thank you for your your submission. You can track its status at  https://github.com/cityofaustin/austindotgov/issues/19.
If you would like to add comments, sign up for a Github account, log in, an visit the URL above."_ 

I believe @mattlangan included this functionality in the service - not sure where to look in the [GitHub API Issue Creator repo](https://github.com/cityofaustin/api-github-issue) to confirm.

**Comment by benweatherman** [comment]
This issue was intended to be the UI portion of the issue so we'll mostly go by the mockups. I put info for the related backend stuff at https://github.com/cityofaustin/joplin/issues/8 (which does have the notion of returning the github URL).

**Comment by ifsimicoded** [comment]
- [ ] UI Views for each state
- [ ] Client form validation
- [ ] Integration with Microservice Form Dispatcher

**Comment by mateoclarke** [comment]
Noting something I'm hearing in the [12/8 sprint review presentation](https://docs.google.com/presentation/d/129RcsygW_JfrdOKdqwCQxdjeNMK6j5Qltk2fj-2-yGQ/edit#slide=id.g32db06c648_0_22).

The research team is articulating a need for analytics to understand form completion rates and where a user might dropoff. We will have to think about how much Google Analytics can do for us in this regard and how this might effect our routing and url params. Perhaps there are other solutions to consider here other than GA?

![screen shot 2017-12-08 at 11 29 03 am](https://user-images.githubusercontent.com/5697474/33777584-0c12ed28-dc0b-11e7-955f-61c74ec45eb4.png)

cc/ @MireyaGalarza

**Comment by benweatherman** [comment]
GA can definitely be used to track custom events. It can be nice to use GA tools to analyze workflow, etc. I've also used [MixPanel](https://mixpanel.com) and [KissMetrics](https://kissmetrics.com) with success.

**Comment by cthibaultatx** [comment]
Content team drafted the feedback form submission confirmation email: https://docs.google.com/document/d/1RIOXqVZpK0VF3AUk3oNxUQfDlxE7diAlmMqYnXC5qsI/edit?usp=sharing

**Comment by cthibaultatx** [comment]
![screen shot 2017-12-11 at 8 31 45 pm](https://user-images.githubusercontent.com/20911665/33864483-6980c21a-deb2-11e7-8868-18d36d7ad8ad.png)
@ifsimicoded updated content for feedback form

**Comment by benweatherman** [comment]
Creating a github issue won't work currently

Here's some code that'll work to send an email instead
```js
fetch('https://coa-test-form-api.herokuapp.com/process/', {
        method: 'POST',
        body: JSON.stringify({
            destination: 'email',
            deliver_to: 'ben.weatherman@austintexas.gov',
            subject: 'ilikeu',
            'other things': 'all these things will show up in the body of the email',
            yolo: 'we can put whatever we want in here',
        }),
        headers: new Headers({
            'Content-Type': 'application/json',
        })
    })
    .then(resp => resp.text())
    .then(console.log)
    .catch(console.log)
```

Here's what you get in the old spam receptacle

![email](https://user-images.githubusercontent.com/272675/35166195-9cc13420-fd16-11e7-89df-63707c7e2b02.png)

**Comment by benweatherman** [comment]
Oh looks like fetch is a thing again (aka we can file issues now):

```
fetch('https://coa-test-form-api.herokuapp.com/process/', {
        method: 'POST',
        body: JSON.stringify({
            destination: 'githubIssue',
            repository: 'janis',
            title: 'ilikeu',
            description: '@ifsimicoded is my hero',
        }),
        headers: new Headers({
            'Content-Type': 'application/json',
        })
    })
    .then(resp => resp.text())
    .then(console.log)
    .catch(console.log)

{"status":"success","body":"Your feedback has been received.","url":"https://github.com/cityofaustin/janis/issues/129"}
```

**Comment by mateoclarke** [comment]
@amenity just created the repo for the fetch body:
https://github.com/cityofaustin/alpha-public-feedback

We should be good to move this forward now.

**Comment by benweatherman** [comment]
Closing in favor of cityofaustin/techstack#109 and cityofaustin/techstack#110
