### ISSUE TITLE
Hack 4 Change Trash API

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/janis#245]
The goal is to replace the widget that we have on this page:
http://alpha.austin.gov/services/bulk-item-pickup

In order to implement this we need to:
- [ ] Create a component that takes in pickup schedule data and displays it in a responsive manner
- [ ] Create a component that allows a user to enter and select their address (with autosuggest/autocomplete)
- [ ] Figure out how to hook all of this up to the recollect API

**Comment by briaguya** [comment]
## Recollect API

### Recycling schedule:
When typing in the address for autocomplete:
```https://recollect.net/api/areas/Austin/services/323/address-suggest?q=1702&locale=en-US&_=1527882407286```
When selecting an address, it appears to do a formatted address search to get an ID
```https://recollect.net/api/places?formatted_address=1702+Taylor+Gaines+St+Unit+B%2C+Austin&parcel_id=39514805&area_id=323&area_name=Austin&place_id=0&svc_id=323&locale=en-US&args=```
when hitting that endpoint, it redirects to:
```https://recollect.net/api/places/9155CF5C-65D4-11E8-891D-DF22E1657EA1/services/323?```
then we get a calendar search endpoint hit:
```https://recollect.net/api/areas/Austin/services/waste/pages/en-US/calendar_search:%7B%22tabbed%22:true%7D.json?widget_config=%7B%22area%22%3A%22Austin%22%2C%22container%22%3A%22%23rCw%22%2C%22page%22%3A%22tabbed_widget%22%2C%22name%22%3A%22wizard%22%7D&_=1527882494973```
^ this one doesn't seem to actually get any specific info
We also get a hit on this endpoint:
```https://recollect.net/api/places/9155CF5C-65D4-11E8-891D-DF22E1657EA1/services/323/events?nomerge=1&hide=reminder_only&after=2018-05-27&before=2018-07-09&locale=en-US&include_message=email&_=1527882518```

**Comment by ifsimicoded** [comment]
@briaguya not sure the best place for this issue to live, but just FYI, https://github.com/cityofaustin/techstack/issues/ is where all the other janis/joplin issues live.
