### ISSUE TITLE
Application block for Recollect

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/janis#26]
Need documentation from Jorge
(512) 974-7784

Got a response!
[recollect-userguide-embedding.pdf](https://github.com/cityofaustin/janis/files/1619920/recollect-userguide-embedding.pdf)
[Widget codes.txt](https://github.com/cityofaustin/janis/files/1619928/Widget.codes.txt)

Above embed script utilizes document.write, which doesn't work for async loaded scripts. Checking with Recollect directly to see if there are async solutions. luke@recollect.net

**Comment by ashleecoa** [comment]
Hey @ifsimicoded the content team is currently working on getting alpha content translated, and it brought something up I believe you were looking into a while ago. When a user is on a translated page, would apps be able to display in that language? Did you find anything regarding Recollect translation in the documentation Jorge sent? Is that addressed in this issue?

**Comment by ifsimicoded** [comment]
I can reach out to their team to see what internationalization features they have available (I've seen Spanish, but I don't have documentation on how to have that automatically set).
That said, we have more to do with translation (how to handle static content like Header, Footer, Headings not stored in Joplin)

**Comment by ashleecoa** [comment]
OK. Does this need to be a separate Github issue?

**Comment by ifsimicoded** [comment]
Closed by #104 
Will reach out to Recollect team to request improvements to load multiple Recollect blocks and not require a page reload.
