### ISSUE TITLE
Topic Page

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/janis#29]
Mocks in sketch file here:
https://drive.google.com/drive/folders/1Xg6739ixhIDrb7MdJAnO4_zCRu3kDmZQ

**Comment by cthibaultatx** [comment]
Topic Page Mock ![mvp_s_3 0_topic](https://user-images.githubusercontent.com/20911665/33965888-244b984c-e023-11e7-84cc-0139d7800cd8.png)

**Comment by ifsimicoded** [comment]
closed by #81
