### ISSUE TITLE
Create separate austin.gov feedback tracker repo

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#31]
issue tracker that will receive public feedback via the feedback form

- [ ] Once this is up and running, send this to our partner Bryan Hirsch at Mass.gov

**Comment by mateoclarke** [comment]
@ifsimicoded, I talked to @cthibaultatx yesterday about where Site Feedback Form data gets saved to an issue. A new repo seemed like the best option.

**Comment by mateoclarke** [comment]
@benweatherman, do we need to create a new repo for feedback of were we just doing to dump issues into either Janis or Joplin? How do we want to handle this for the feedback form?

**Comment by benweatherman** [comment]
I'm not sure what the vision for feedback is. I think it depends on how we're going to manage it. Is feedback only intended for design and development changes? Will people use it to ask general questions?

Maybe @amenity has some insight?

**Comment by mateoclarke** [comment]
Yeah I think the idea was feedback could be super broad and there was even talk at some point about 311 having a role in this process. It seems like we'd want this inbox of feedback to be managed at the Product Owner lever before it would get assigned to any Designers, Content Writers or Devs. 

@amenity how do you feel about taking over this issue and creating the Github repo for feedback issues to land?

**Comment by amenity** [comment]
Yup! The idea was that issues go to Janis, Joplin, (a new) content repo, and maaaaybe (a new) translation repo - again, translation remains a mystery to me, but we could just configure github to email CPIO language team when an issue goes there. 

I'm not sure if they should go directly to repos depending on what the user selects for the radio button, or whether they should go into a general feedback repo and then manually sorted. We do want to present the submitter with a URL where they can see their issue forever - I don't know if moving or recreating an issue could preserve that, or if we'd add a link to the issue at the initial URLto the new URL. 

In general, this isn't super-defined, but my preference would be to implement something easy/basic and test/iterate.

**Comment by benweatherman** [comment]
Briefly talked with @mateoclarke and thought this might be a good way to proceed:

1. @amenity create a repo with a name that residents will like
2. We'll send all issues to that repo
3. Someone (@amenity?) will be responsible for making sure those issues are scheduled, answered, closed, etc. Basically be the communication to the resident.
4. We'll create issues in other repos if needed and can link them back to the original issue (e.g. when creating an issue in joplin say "This is part of resident issue cityofaustin/cool-new-repo-name#issue-number")

**Comment by amenity** [comment]
https://github.com/cityofaustin/alpha-public-feedback
