### ISSUE TITLE
Department page template

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#34]
- [ ] Leave out project tracker section

![mvp_s_2 0_dept](https://user-images.githubusercontent.com/20911665/34007369-26e7d0ee-e0c7-11e7-8b3a-7c369c6ba20c.png)

**Comment by ifsimicoded** [comment]
Left in the project tracker section, but it can easily be commented out/removed. 
Closed by #83

**Comment by ifsimicoded** [comment]
Left in the project tracker section, but it can easily be commented out/removed.
Closed by #83
