### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#36]
![search-flow_14dec2017](https://user-images.githubusercontent.com/20911665/34009392-5c45a0c0-e0ce-11e7-80f2-6cb77e24b37e.png)

**Comment by mateoclarke** [comment]
For now, when you click the search icon, we navigate you to the Search Results Page. Search lives on its own route `/search` kind of like whats illustrated in the 4th mock above.

@cthibaultatx is going to think about how we design the search in the global nav to be more dynamic, without a path routing.

**Comment by mateoclarke** [comment]
duplicate of cityofaustin/techstack#258
