### ISSUE TITLE
Update 'related services' section

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#41]
We observed a handful of residents using the new digital services. One person referred to 'related services' and the 'feedback request form' as the _footer_. Another person using a tablet did not scroll down to the 'related services' section and so was never able to use it to discover and access similar services. Problem is that users are not recognizing 'related services' as part of the service page experience–it feels separate, like a footer. And on our end–'related services' is the primary next step we want users to take.

I imagined (A) moving the 'related service' content into the right column, beneath 'contact', but it felt like too much information. Of course, we can't be sure until residents test, but instead–let's (B) change the attributes of the 'related services' section so that when a user gets to the end of a service- they continue to scroll down and read over 'related services', believing that it is an inherent part of that service.

updates in mocks:
- change 'related services' section background to match service content background
- change service tile color to #0A71AE $color-primary
- change service tile type and chevrons to #ffffff white
- change 'related services' section title to: "Check out related city services"
**there's a change in column layout included in the mocks but I'll detail that in a separate issue**

![mvp_l_1 1_service_15dec2017](https://user-images.githubusercontent.com/20911665/34118843-b124d786-e3e5-11e7-9b83-b3377172a86d.png)
![mvp_m_1 1_service_15dec2017](https://user-images.githubusercontent.com/20911665/34118844-b132c198-e3e5-11e7-8023-4da9319a2024.png)
![mvp_s_1 1_service_15dec2017](https://user-images.githubusercontent.com/20911665/34118845-b1446704-e3e5-11e7-8ab4-7532ca81be8c.png)

**Comment by ifsimicoded** [comment]
@cthibaultatx any ideas on the related service buttons for visited and focused state?
