### ISSUE TITLE
Add map to contact section

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#76]
![screen shot 2018-01-09 at 7 44 18 am](https://user-images.githubusercontent.com/20911665/34723931-cd2402ee-f511-11e7-9287-9090d152b678.png)

- [ ] map is 284 x 120, aligns left with copy

- [ ] map zoom = 16z a la google maps

Map pin and color specs could be worked out between front-end team and ux designer, using Diana's ctx floods documentation as a guide.

![mvp_s_1 1_service](https://user-images.githubusercontent.com/20911665/34723922-c6ebfdbe-f511-11e7-9148-ebb6cbf074ea.png)

**Comment by ifsimicoded** [comment]
@cthibaultatx When you get a sec, let's play with sizing. The initial sizing you provided, was a bit difficult to see and I need more info on the tablet & desktop view. This is just easier to determine live, than in a mock.

**Comment by ifsimicoded** [comment]
Closed by #107
