### ISSUE TITLE
Collapse contact hours and make expandable

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/janis#79]
![screen shot 2018-01-09 at 8 55 47 am](https://user-images.githubusercontent.com/20911665/34726930-0af59fd4-f51b-11e7-93f7-3949554a146e.png)

- [ ] defaults to current day of the week plus corresponding hours

- [x] when expanded, shows days following meaning if it's Wednesday, the expanded list starts with Wednesday, ends with Tuesday

- [ ] once expanded, current day of week and hours is bolded to Open Sans semi-bold, weight 600

Not sure if the day should also be formatted in p-link style (highlighted and underlined in blue). Referencing google- they only link the hours, not the day.

## Resident Value
doesn't bombard resident with unrelated information and gives them control to see more if desired

**Comment by ifsimicoded** [comment]
@cthibaultatx We've been using Montserrat for our san font face based on the mocks. Do we need to also use Open Sans? For each new font we load, the user has to download that font resource so limiting the number of fonts we use is critical for performance/speed-experience.
