### ISSUE TITLE
Provide a common pattern for fetching data for Pages

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/janis#90]
We need to manually trigger a fetch for data is some consistent places at the page level. There is an abstraction waiting for us here.

Examples:
https://github.com/cityofaustin/janis/pull/81#discussion_r161300676
https://github.com/cityofaustin/janis/pull/84#pullrequestreview-88593491

**Comment by ifsimicoded** [comment]
Closing this as we're no longer doing data fetches on page load. We're currently using React static for data fetches for static page rendering and may move to Next.js
