### ISSUE TITLE
Add PropTypes to components

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/janis#91]
We started doing it in another project, but then didn't continue. Seems like an easy thing to add and get some benefit when it comes to documentation and better warnings.

Discussion: https://github.com/cityofaustin/janis/pull/83/files/9f470ad842b1d6155c1d06df44b914ff1f9a8c7e#diff-9eb9f765c7bf27ae57a46c37f875a3b1

**Comment by ifsimicoded** [comment]
Duplicate of https://github.com/cityofaustin/techstack/issues/244
